export const CHECK_TOKEN_START = 'CHECK_TOKEN_START';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAIL = 'CHECK_TOKEN_FAIL';
export const CHECK_TOKEN_RESET = 'CHECK_TOKEN_RESET';
